- name: Configure Apache Web Server
  hosts: all
  become: true
  vars:
    apache_package_ubuntu: apache2
    apache_package_redhat: httpd
    apache_port: 8080
    ubuntu_config_file: /etc/apache2/ports.conf
    redhat_config_file: /etc/httpd/conf/httpd.conf
  tasks:
    - name: Install Apache on Ubuntu
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.apt:
        name: "{{ apache_package_ubuntu }}"
        state: present
        update_cache: yes

    - name: Install Apache on RedHat
      when: ansible_distribution == "RedHat"
      ansible.builtin.dnf:
        name: "{{ apache_package_redhat }}"
        state: present

    - name: Ensure Apache is running on Ubuntu
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.service:
        name: "{{ apache_package_ubuntu }}"
        state: started
        enabled: yes

    - name: Ensure Apache is running on RedHat
      when: ansible_distribution == "RedHat"
      ansible.builtin.service:
        name: "{{ apache_package_redhat }}"
        state: started
        enabled: yes

    - name: Configure Apache to listen on port 8080 (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.replace:
        path: "{{ ubuntu_config_file }}"
        regexp: '^Listen\s+80$'
        replace: "Listen {{ apache_port }}"

    - name: Configure Apache to listen on port 8080 (RedHat)
      when: ansible_distribution == "RedHat"
      ansible.builtin.replace:
        path: "{{ redhat_config_file }}"
        regexp: '^Listen\s+80$'
        replace: "Listen {{ apache_port }}"

    - name: Restart Apache to apply port change (Ubuntu)
      when: ansible_distribution == "Ubuntu"
      ansible.builtin.service:
        name: "{{ apache_package_ubuntu }}"
        state: restarted

    - name: Restart Apache to apply port change (RedHat)
      when: ansible_distribution == "RedHat"
      ansible.builtin.service:
        name: "{{ apache_package_redhat }}"
        state: restarted
